### ISSUE TITLE
grid of plots?

### ISSUE THREAD

**Issue by SteveGoldstein** [AFIDSI/COVID-19_WastewaterAnalysis#2]
For the interactive active plots with the 9 sample points for each day:   It would be great if there's an easy way to display several at once on a grid.   Even better:  interactively select which plants to display and the dimensions of the grid.

**Comment by MarlinRLee** [comment]
Added with some issues. The size of the individual's plot changes a bit depending on the dimensions of the grid selected. The issue is created because some dimensions don't work. IE 9 rows with 10 graphs return 5 rows instead.
![3by4Grid](https://user-images.githubusercontent.com/76969165/113490069-848c0300-948d-11eb-8b6d-906e29ced123.jpeg)
![5by2](https://user-images.githubusercontent.com/76969165/113490072-89e94d80-948d-11eb-983e-211968b53dcc.jpg)
